app:
  image: cloudhotspot/sampledjangoapp
  links:
    - db
  ports:
    - 8000:8000

db:
  image: mysql
  hostname: db
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: password 
    MYSQL_DATABASE: app_db
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: password
