app:
  image: ${REPO_NS}/${APP_NAME}-release:latest
  extra_hosts:
    bob: 8.8.8.8
  links:
    - db
  environment:
    DJANGO_SETTINGS_MODULE: mysite.settings.base
    MYSQL_ROOT_PASSWORD: pass1234 
    MYSQL_DATABASE: sampledjangoapp
    MYSQL_USER: sampledjangoapp
    MYSQL_PASSWORD: pass1234
    MYSQL_HOST: db

db:
  image: mysql
  hostname: db
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: pass1234 
    MYSQL_DATABASE: sampledjangoapp
    MYSQL_USER: sampledjangoapp
    MYSQL_PASSWORD: pass1234