app:
  image: mycompany/myapp:latest

db:
  image: mysql
  hostname: db
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: password 
    MYSQL_DATABASE: app_db
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: password

cache:
  image: mycompany/myapp-test:latest
  container_name: mycompany_myapp_cache
  volumes:
    - /tmp/mycompany_myapp_cache:/cache
  entrypoint: "true"