app:
  image: mycompany/myapp:latest

db:
  image: mysql
  hostname: db
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: password 
    MYSQL_DATABASE: app_db
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: password

agent:
  image: mycompany/myapp-agent:latest
  volumes:
    - ../ansible/agent:/ansible
  command: site.yml --extra-vars="probe_host=db probe_port=3306"