app:
  image: "mycompany/myapp-dev:latest"
  volumes_from:
    - cache
  volumes:
    - ../src:/application
  environment:
    DJANGO_SETTINGS_MODULE: mysite.settings.test
    MYSQL_USER: root
    MYSQL_PASSWORD: pass1234

cache:
  image: mycompany/myapp-dev:latest
  volumes:
    - /tmp/mycompany_myapp_cache:/cache
  entrypoint: "true"

agent:
  image: mycompany/myapp-agent:latest
  links:
    - db
  volumes:
    - ../ansible/agent:/ansible
  command: site.yml --extra-vars="probe_host=db probe_port=3306"

builder:
  image: mycompany/myapp-dev:latest
  volumes:
    - ../src:/application
    - ../target:/wheelhouse
  volumes_from:
    - cache
  entrypoint: "entrypoint.sh"
  command: ["pip", "wheel", "."]