app:
  image: ${REPO_NS}/${APP_NAME}-${GIT_BRANCH}-dev:latest
  volumes_from:
    - cache
  volumes:
    - ../src:/application
  environment:
    DJANGO_SETTINGS_MODULE: mysite.settings.test
    MYSQL_USER: root
    MYSQL_PASSWORD: pass1234
    NOSE_INCLUDE_EXE: 1

cache:
  image: ${REPO_NS}/${APP_NAME}-${GIT_BRANCH}-dev:latest
  volumes:
    - /tmp/${REPO_NS}_${APP_NAME}_cache:/cache
  entrypoint: "true"

agent:
  image: ${REPO_NS}/${APP_NAME}-${GIT_BRANCH}-agent:latest
  links:
    - db
  volumes:
    - ../ansible/agent:/ansible
  command: site.yml --extra-vars="probe_host=db probe_port=3306"

builder:
  image: ${REPO_NS}/${APP_NAME}-${GIT_BRANCH}-dev:latest
  volumes:
    - ../src:/application
    - ../target:/wheelhouse
  volumes_from:
    - cache
  entrypoint: "entrypoint.sh"
  command: ["pip", "wheel", "."]