app:
  extends:
    file: common.yml
    service: app
  links:
    - db
  ports:
    - 8000:8000

db:
  extends:
    file: common.yml
    service: db

agent:
  extends:
    file: common.yml
    service: agent
  links:
    - db