app:
  extends:
    file: common.yml
    service: app
  links:
    - db
  ports:
    - 8000:8000
  volumes_from:
    - static
  command: uwsgi --http :8000 --module mysite.wsgi --static-map /static=/var/www/mysite/static
  environment:
    DJANGO_SETTINGS_MODULE: mysite.settings.production

db:
  extends:
    file: common.yml
    service: db

static:
  image: mycompany/myapp-release:latest
  volumes:
    - /var/www/mysite/
  entrypoint: "true"

agent:
  extends:
    file: common.yml
    service: agent
  links:
    - db