app:
  ports:
    - 8000:8000
  volumes_from:
    - static
  command: uwsgi --http :8000 --module mysite.wsgi --static-map /static=/var/www/mysite/static --master
  environment:
    DJANGO_SETTINGS_MODULE: mysite.settings.release

static:
  image: cloudhotspot/django-sample-app-release:latest
  volumes:
    - /var/www/mysite/
  entrypoint: "true"

agent:
  image: cloudhotspot/django-sample-app-agent:latest
  links:
    - db
  volumes:
    - ../ansible/agent:/ansible
  command: site.yml --extra-vars="probe_host=db probe_port=3306"