app:
  extends:
    file: common.yml
    service: app
  image: mycompany/myapp-test:latest
  links:
    - db
  volumes_from:
    - cache
  volumes:
    - ../src:/application

db:
  extends:
    file: common.yml
    service: db

cache:
  image: mycompany/myapp-test:latest
  container_name: mycompany_myapp_cache
  volumes:
    - /tmp/mycompany_myapp_cache:/cache
  entrypoint: "true"

agent:
  extends:
    file: common.yml
    service: agent
  links:
    - db

builder:
  image: mycompany/myapp-builder:latest
  volumes:
    - ../src:/application
  volumes_from:
    - cache