app:
  extends:
    file: common.yml
    service: app
  image: mycompany/myapp-test:latest
  links:
    - db
  volumes_from:
    - cache
  volumes:
    - ../src:/application

cache:
  extends:
    file: common.yml
    service: cache

db:
  extends:
    file: common.yml
    service: db

agent:
  image: mycompany/myapp-agent:latest
  links:
    - db
  volumes:
    - ../ansible/agent:/ansible
  command: site.yml --extra-vars="probe_host=db probe_port=3306"